# This workflow generates new puzzles and their respecitve solutions
# and saves them in repository
name: Generate daily puzzles

on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"

jobs:
  generate_puzzle_and_pr:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.17.0'

      - name: Generate puzzles
        run: sh generate_puzzles.sh

      - name: Commit files
        id: commit
        run: |
          git config --local user.email ${{ secrets.EMAIL }}
          git config --local user.name ${{ secrets.USERNAME }}
          git config --local user.password ${{ secrets.TOKEN }}
          git add --all
          if [-z "$(git status --porcelain)"]; then
            echo "::set-output name=push::false"
          else
            git commit -m "Todays puzzles" -a
            echo "::set-output name=push::true"
          fi
        shell: bash

      - name: Push changes
        run: git push

#       - name: Push changes
#         if: steps.commit.outputs.push == 'true'
#         uses: ad-m/github-push-action@master
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}